import type { CanonicalSignal, CanonicalSummary, Direction, HistoryResponse, PerformanceBreakdown, PerformanceResponse, StrategyEndpointResponse, StrategyId } from "../../types/canonical.ts";
const isRecord = (value: unknown): value is Record<string, unknown> => typeof value === "object" && value !== null;
const strategies: StrategyId[] = ["strong_sd_magnet", "swing_liquidity", "swing_forecast"];
const directions: Direction[] = ["BUY", "SELL"];
const statuses = ["PENDING", "ACTIVE", "WIN", "LOSS", "AMBIGUOUS"] as const;
const results = ["WIN", "LOSS", "AMBIGUOUS"] as const;
function requiredString(value: unknown, field: string): string { if (typeof value !== "string" || !value) throw new Error(`INVALID_RESPONSE:${field}`); return value; }
function finite(value: unknown, field: string): number { const n = Number(value); if (!Number.isFinite(n)) throw new Error(`INVALID_RESPONSE:${field}`); return n; }
function nullableString(value: unknown, field: string): string | null { if (value == null) return null; return requiredString(value, field); }
function summary(value: unknown): CanonicalSummary { if (!isRecord(value)) throw new Error("INVALID_RESPONSE:summary"); return { totalSignals: finite(value.totalSignals, "summary.totalSignals"), wins: finite(value.wins, "summary.wins"), losses: finite(value.losses, "summary.losses"), open: finite(value.open, "summary.open"), pending: finite(value.pending, "summary.pending"), active: finite(value.active, "summary.active"), ambiguous: finite(value.ambiguous, "summary.ambiguous"), winRate: finite(value.winRate, "summary.winRate") }; }
export function parseSignal(value: unknown): CanonicalSignal { if (!isRecord(value)) throw new Error("INVALID_RESPONSE:signal"); const strategy = requiredString(value.strategy, "signal.strategy") as StrategyId; if (!strategies.includes(strategy)) throw new Error("INVALID_RESPONSE:signal.strategy"); const direction = requiredString(value.direction, "signal.direction").toUpperCase() as Direction; if (!directions.includes(direction)) throw new Error("INVALID_RESPONSE:signal.direction"); const status = requiredString(value.status, "signal.status") as CanonicalSignal["status"]; if (!statuses.includes(status)) throw new Error("INVALID_RESPONSE:signal.status"); const result = value.result == null ? null : String(value.result).toUpperCase() as CanonicalSignal["result"]; if (result !== null && !results.includes(result)) throw new Error("INVALID_RESPONSE:signal.result"); if (!Array.isArray(value.takeProfit) || value.takeProfit.length === 0) throw new Error("INVALID_RESPONSE:signal.takeProfit"); return { id: requiredString(value.id, "signal.id"), identityKey: typeof value.identityKey === "string" ? value.identityKey : undefined, strategy, symbol: requiredString(value.symbol, "signal.symbol"), timeframe: requiredString(value.timeframe, "signal.timeframe"), direction, status, signalTime: requiredString(value.signalTime, "signal.signalTime"), candleTime: requiredString(value.candleTime, "signal.candleTime"), entryCandleTime: nullableString(value.entryCandleTime, "signal.entryCandleTime"), entryPrice: finite(value.entryPrice, "signal.entryPrice"), takeProfit: value.takeProfit.map((n, i) => finite(n, `signal.takeProfit[${i}]`)), stopLoss: finite(value.stopLoss, "signal.stopLoss"), result, resultPrice: value.resultPrice == null ? null : finite(value.resultPrice, "signal.resultPrice"), resultTime: nullableString(value.resultTime, "signal.resultTime"), createdAt: requiredString(value.createdAt, "signal.createdAt"), updatedAt: requiredString(value.updatedAt, "signal.updatedAt"), lockedAt: nullableString(value.lockedAt, "signal.lockedAt"), lastEvaluatedCandleTime: nullableString(value.lastEvaluatedCandleTime, "signal.lastEvaluatedCandleTime"), metadata: isRecord(value.metadata) ? value.metadata : undefined }; }
export function parseHistoryResponse(value: unknown): HistoryResponse { if (!isRecord(value) || value.success !== true || !Array.isArray(value.records)) throw new Error("INVALID_RESPONSE:history"); return { success: true, summary: summary(value.summary), records: value.records.map(parseSignal) }; }
function breakdown(value: unknown, field: string): PerformanceBreakdown { try { return summary(value); } catch { throw new Error(`INVALID_RESPONSE:${field}`); } }
export function parsePerformanceResponse(value: unknown): PerformanceResponse { if (!isRecord(value) || value.success !== true || !isRecord(value.summary) || !isRecord(value.strategyPerformance) || !isRecord(value.directionPerformance)) throw new Error("INVALID_RESPONSE:performance"); const strategyPerformance = {} as PerformanceResponse["strategyPerformance"]; for (const strategy of strategies) strategyPerformance[strategy] = breakdown(value.strategyPerformance[strategy], `strategyPerformance.${strategy}`); const directionPerformance = {} as PerformanceResponse["directionPerformance"]; for (const direction of directions) directionPerformance[direction] = breakdown(value.directionPerformance[direction], `directionPerformance.${direction}`); return { success: true, summary: summary(value.summary), strategyPerformance, directionPerformance }; }
export interface ParsedStrategyEndpointResponse extends Omit<StrategyEndpointResponse, "canonicalSignal"> { canonicalSignal: CanonicalSignal | null; }
export function parseStrategyEndpointResponse(value: unknown): ParsedStrategyEndpointResponse { if (!isRecord(value) || value.success !== true || typeof value.symbol !== "string" || typeof value.interval !== "string") throw new Error("INVALID_RESPONSE:strategy_endpoint"); const canonicalValue = value.canonicalSignal; const canonicalSignal = canonicalValue == null ? null : isRecord(canonicalValue) && typeof canonicalValue.error === "string" ? null : parseSignal(canonicalValue); return { success: true, symbol: value.symbol, interval: value.interval, canonicalSignal, engine: isRecord(value.engine) ? value.engine : undefined, strategy: isRecord(value.strategy) ? value.strategy : undefined, market: isRecord(value.market) ? value.market : undefined, tradePlan: isRecord(value.tradePlan) ? value.tradePlan : value.tradePlan === null ? null : undefined, signal: isRecord(value.signal) ? value.signal : value.signal === null ? null : undefined, nextCandle: isRecord(value.nextCandle) ? value.nextCandle : undefined, closedCandle: isRecord(value.closedCandle) ? value.closedCandle : undefined }; }
